name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub PostgreSQL image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5439:5432
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5439/postgres

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.

      - name: Test Deno is Working
        run: deno run https://deno.land/std@0.198.0/examples/welcome.ts

      - name: Run Migration
        run: deno run -A src/infrastucture/database/migration/base.ts --env

      - name: Test API
        run: deno task test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.

      - name: Test Deno is Working
        run: deno run https://deno.land/std@0.198.0/examples/welcome.ts

      - name: Lint
        run: deno lint

      - name: Format
        run: deno fmt --check

      - name: Check types
        run: deno check ./
